spring:
  mail:
    host: smtp.gmail.com
    password: 0044javaraghu2200
    port: 587
    properties:             
      mail:
        smtp:
          starttls:
            enable: true
    username: javaraghu2018@gmail.com
